ALTER TYPE "VehicleImageKey" ADD VALUE IF NOT EXISTS 'BLACK_BENTLEY';
ALTER TYPE "VehicleImageKey" ADD VALUE IF NOT EXISTS 'GREEN_PORSCHE_911';
ALTER TYPE "VehicleImageKey" ADD VALUE IF NOT EXISTS 'BROWN_MAYBACH';
ALTER TYPE "VehicleImageKey" ADD VALUE IF NOT EXISTS 'ORANGE_AUDI_R8';
ALTER TYPE "VehicleImageKey" ADD VALUE IF NOT EXISTS 'BLACK_RANGE_ROVER';

ALTER TYPE "FuelType" ADD VALUE IF NOT EXISTS 'GASOLINE';
